#!/usr/bin/env python3
"""Emit synthesizable SystemVerilog from an executable RTLIL-subset plan."""

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

from executable_graph import EXECUTABLE_SCHEMA, ExecutableGraphError


class GraphEmitError(ValueError):
    pass


REPOSITORY_ROOT = Path(__file__).resolve().parent


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _manifest_record(path: Path, root: Path = REPOSITORY_ROOT) -> Dict[str, Any]:
    resolved = Path(path).resolve()
    try:
        relative = resolved.relative_to(Path(root).resolve()).as_posix()
        return {"path": relative, "external": False, "sha256": _sha256(resolved)}
    except ValueError:
        return {"path": str(resolved), "external": True, "sha256": _sha256(resolved)}


def validate_manifest(path: Path, root: Path = REPOSITORY_ROOT) -> Dict[str, Any]:
    """Validate every recorded dependency, resolving repository paths at root."""
    try:
        manifest = json.loads(Path(path).read_text())
    except (OSError, ValueError) as exc:
        raise GraphEmitError("cannot read manifest {}: {}".format(path, exc))
    if manifest.get("schema") != "fu-graph-rtl-manifest/v1":
        raise GraphEmitError("manifest schema is not fu-graph-rtl-manifest/v1")
    if manifest.get("template_backed") is not False or manifest.get("graph_to_rtl_status") != "executable":
        raise GraphEmitError("manifest does not describe an executable generic realization")
    checked = {}
    for name, record in (manifest.get("evidence") or {}).items():
        if not isinstance(record, dict) or not isinstance(record.get("path"), str):
            raise GraphEmitError("manifest record {} is malformed".format(name))
        target = Path(record["path"]) if record.get("external") else Path(root) / record["path"]
        if not target.is_file():
            raise GraphEmitError("manifest dependency is missing: {}".format(record["path"]))
        actual = _sha256(target)
        if actual != record.get("sha256"):
            raise GraphEmitError("manifest hash mismatch for {}".format(record["path"]))
        checked[name] = {"path": record["path"], "external": bool(record.get("external")), "sha256": actual}
    return {"valid": True, "checked": len(checked), "records": checked}


def _safe(value: str) -> str:
    result = re.sub(r"[^A-Za-z0-9_]", "_", str(value))
    return "w_" + result if not result or result[0].isdigit() else "w_" + result


def _width(node: Dict[str, Any]) -> int:
    width = node.get("width")
    if not isinstance(width, int) or width < 1:
        raise GraphEmitError("node {} has no usable width".format(node.get("id")))
    return width


def _load_plan(path: Path) -> Dict[str, Any]:
    try:
        plan = json.loads(path.read_text())
    except (OSError, ValueError) as exc:
        raise GraphEmitError("cannot read executable graph: {}".format(exc))
    if plan.get("schema") != EXECUTABLE_SCHEMA or not plan.get("hardware_status", {}).get("executable"):
        raise GraphEmitError("only an executable graph plan can be emitted")
    if plan.get("hardware_status", {}).get("template_backed"):
        raise GraphEmitError("template-backed plans are not accepted by the generic emitter")
    return plan


def emit(plan: Dict[str, Any]) -> str:
    nodes = {node["id"]: node for node in plan.get("nodes", [])}
    if len(nodes) != len(plan.get("nodes", [])):
        raise GraphEmitError("executable graph contains duplicate node IDs")
    edges = plan.get("edges", [])
    incoming: Dict[str, List[Dict[str, Any]]] = {node_id: [] for node_id in nodes}
    for edge in edges:
        if edge.get("src") not in nodes or edge.get("dst") not in nodes:
            raise GraphEmitError("edge references a missing executable node")
        incoming[edge["dst"]].append(edge)
    for values in incoming.values():
        values.sort(key=lambda edge: (edge.get("dst_port", ""), edge.get("src", ""), edge.get("src_port", "")))
    outputs = plan.get("outputs", [])
    output_names = {item["name"] for item in outputs}
    port_nodes = [node for node in nodes.values() if node.get("kind") in ("port_in", "port_out")]
    inputs = sorted((node for node in port_nodes if node["kind"] == "port_in"), key=lambda n: n["label"])
    if len({node["label"] for node in inputs}) != len(inputs) or len(output_names) != len(outputs):
        raise GraphEmitError("executable ports are not uniquely named")
    if not isinstance(plan.get("top"), str) or not plan["top"]:
        raise GraphEmitError("executable graph has no requested generated top")
    lines = ["// Generated by graph_rtl_emit.py from fu-executable-graph/v1.",
             "// This file is generic RTLIL-subset output; no template body is used.",
             "module {} (".format(plan["top"])]
    declarations = []
    for node in inputs:
        width = _width(node)
        declarations.append("    input logic [{}:0] {}".format(width - 1, node["label"]) if width > 1 else "    input logic {}".format(node["label"]))
    for item in sorted(outputs, key=lambda item: item["name"]):
        width = int(item["width"])
        declarations.append("    output logic [{}:0] {}".format(width - 1, item["name"]) if width > 1 else "    output logic {}".format(item["name"]))
    lines.append(",\n".join(declarations)); lines.append(");")
    internal = [node for node in nodes.values() if node.get("kind") not in ("port_in", "port_out")]
    for node in sorted(internal, key=lambda n: n["id"]):
        lines.append("    logic [{}:0] {};".format(_width(node) - 1, _safe(node["id"])))
    lines.append("")

    def signal(node_id: str, seen=None) -> str:
        node = nodes[node_id]
        if node.get("kind") == "port_in":
            return node["label"]
        if node.get("kind") == "port_out":
            seen = set() if seen is None else set(seen)
            if node_id in seen:
                raise GraphEmitError("output connection is cyclic")
            seen.add(node_id)
            output_edges = incoming.get(node_id, [])
            if len(output_edges) != 1:
                raise GraphEmitError("output {} has {} drivers".format(node.get("label"), len(output_edges)))
            return signal(output_edges[0]["src"], seen)
        return _safe(node_id)

    for node_id in plan.get("topological_order", []):
        node = nodes.get(node_id)
        if node is None or node.get("kind") in ("port_in", "port_out"):
            continue
        kind = node.get("kind")
        vals = {edge.get("dst_port"): signal(edge["src"]) for edge in incoming[node_id]}
        target = _safe(node_id)
        if kind == "const":
            value = str((node.get("attrs") or {}).get("value", "0"))
            lines.append("    assign {} = {}'b{};".format(target, _width(node), value))
        elif kind == "zero_extend":
            if "A" not in vals:
                raise GraphEmitError("zero extension {} has no input".format(node_id))
            source_width = next(edge["width"] for edge in incoming[node_id] if edge.get("dst_port") == "A")
            if source_width >= _width(node):
                raise GraphEmitError("zero extension {} is not widening".format(node_id))
            lines.append("    assign {} = {{{{{}{{1'b0}}}}, {}}};".format(target, _width(node) - source_width, vals["A"]))
        elif kind == "slice":
            if set(vals) != {"A"}:
                raise GraphEmitError("slice {} lacks its ordered input".format(node_id))
            source_lsb = (node.get("attrs") or {}).get("source_lsb")
            if not isinstance(source_lsb, int) or source_lsb < 0:
                raise GraphEmitError("slice {} lacks a proven source range".format(node_id))
            source_node = next(edge["src"] for edge in incoming[node_id] if edge.get("dst_port") == "A")
            source_width = _width(nodes[source_node])
            if source_lsb + _width(node) > source_width:
                raise GraphEmitError("slice {} exceeds its source width".format(node_id))
            high = source_lsb + _width(node) - 1
            lines.append("    assign {} = {}[{}:{}];".format(target, vals["A"], high, source_lsb))
        elif kind == "$mul":
            if set(vals) != {"A", "B"}:
                raise GraphEmitError("multiplier {} lacks ordered operands".format(node_id))
            lines.append("    assign {} = {} * {};".format(target, vals["A"], vals["B"]))
        elif kind == "$add":
            if set(vals) != {"A", "B"}:
                raise GraphEmitError("adder {} lacks ordered operands".format(node_id))
            lines.append("    assign {} = {} + {};".format(target, vals["A"], vals["B"]))
        elif kind == "$not":
            if set(vals) != {"A"}:
                raise GraphEmitError("not {} lacks its ordered operand".format(node_id))
            lines.append("    assign {} = ~{};".format(target, vals["A"]))
        elif kind == "$xor":
            if set(vals) != {"A", "B"}:
                raise GraphEmitError("xor {} lacks ordered operands".format(node_id))
            lines.append("    assign {} = {} ^ {};".format(target, vals["A"], vals["B"]))
        elif kind == "concat":
            segments = []
            for edge in incoming[node_id]:
                port = edge.get("dst_port", "")
                if not port.startswith("SEG_"):
                    raise GraphEmitError("concat {} has an undeclared segment".format(node_id))
                try:
                    bit_lsb = int(port[4:])
                except ValueError:
                    raise GraphEmitError("concat {} has an invalid segment port".format(node_id))
                positions = sorted((edge.get("attrs") or {}).get("bit_positions", []))
                source_positions = sorted((edge.get("attrs") or {}).get("source_bit_positions", []))
                if len(positions) != edge.get("width") or len(source_positions) != edge.get("width") or not positions:
                    raise GraphEmitError("concat {} lacks lossless source bit positions".format(node_id))
                source_width = _width(nodes[edge["src"]])
                if len(positions) > source_width or positions[-1] >= _width(node):
                    raise GraphEmitError("concat {} has unsafe source or destination positions".format(node_id))
                source = signal(edge["src"])
                # Yosys groups source bits in increasing source order. Split
                # sparse destination positions into contiguous runs, retaining
                # the source slice that drives each run.
                end = len(positions) - 1
                while end >= 0:
                    start = end
                    while (start > 0 and positions[start] == positions[start - 1] + 1 and
                           source_positions[start] == source_positions[start - 1] + 1):
                        start -= 1
                    high, low = source_positions[end], source_positions[start]
                    if low == 0 and high == source_width - 1 and len(positions) == source_width:
                        value = source
                    elif high == low:
                        value = "{}[{}]".format(source, high)
                    else:
                        value = "{}[{}:{}]".format(source, high, low)
                    segments.append((positions[start], value))
                    end = start - 1
            if not segments:
                raise GraphEmitError("concat {} has no segments".format(node_id))
            lines.append("    assign {} = {{{}}};".format(target, ", ".join(value for _lsb, value in sorted(segments, reverse=True))))
        elif kind == "$mux":
            if set(vals) != {"A", "B", "S"}:
                raise GraphEmitError("mux {} lacks A/B/S".format(node_id))
            lines.append("    assign {} = {} ? {} : {};".format(target, vals["S"], vals["B"], vals["A"]))
        else:
            raise GraphEmitError("unsupported executable node kind {}".format(kind))
    for item in sorted(outputs, key=lambda item: item["name"]):
        source_node = nodes.get(item["source_node"])
        if source_node is None:
            raise GraphEmitError("explicit output {} references a missing node".format(item["name"]))
        if source_node.get("kind") == "port_out":
            output_edges = incoming.get(item["source_node"], [])
            if len(output_edges) != 1:
                raise GraphEmitError("explicit output {} has {} drivers".format(item["name"], len(output_edges)))
            source_signal = signal(output_edges[0]["src"])
        else:
            source_signal = signal(item["source_node"])
        lines.append("    assign {} = {};".format(item["name"], source_signal))
    lines += ["endmodule", ""]
    return "\n".join(lines)


def write_manifest(path: Path, plan_path: Path, output_path: Path, evidence: Dict[str, Path]) -> Path:
    records = {}
    for name, item in evidence.items():
        records[name] = _manifest_record(item)
    records["executable_graph"] = _manifest_record(plan_path)
    records["generated_rtl"] = _manifest_record(output_path)
    manifest = {"schema": "fu-graph-rtl-manifest/v1", "template_backed": False,
                "graph_to_rtl_status": "executable", "evidence": records}
    path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    return path


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("plan", type=Path); parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument("--graph-a", type=Path, required=True); parser.add_argument("--graph-b", type=Path, required=True)
    parser.add_argument("--match", type=Path, required=True); parser.add_argument("--merge", type=Path, required=True)
    parser.add_argument("--control", type=Path, required=True); parser.add_argument("--manifest", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        plan = _load_plan(args.plan)
        text = emit(plan)
        args.output.parent.mkdir(parents=True, exist_ok=True); args.output.write_text(text)
        write_manifest(args.manifest, args.plan, args.output, {"graph_a": args.graph_a, "graph_b": args.graph_b,
            "match": args.match, "merge": args.merge, "control_spec": args.control,
            "emitter": Path(__file__).resolve()})
        print("wrote {} and {}".format(args.output, args.manifest))
    except (GraphEmitError, OSError) as exc:
        print("graph RTL emission failed: {}".format(exc), file=sys.stderr); return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
