#!/usr/bin/env python3
"""Timing-closure sweep: measure a functional unit's *achievable* fmax.

Why this exists
---------------
A single synthesis run reports the delay of the netlist the tool happened to
produce under one constraint -- not the design's capability.  Yosys/ABC map for
area when the timing target is slack, so a loose SDC yields a slow netlist and a
"max frequency" that is really a statement about the SDC.  The original flow
constrained two 45 nm ALUs at 50 ns, ~30x their critical path, and both reported
~85 MHz despite one being 52% slower in logic.  That number was the constraint.

The standard methodology is to sweep the clock constraint and find the tightest
period the design can still close at, re-synthesizing at each point so the tool
actually optimizes for delay.  This module does that with a binary search.

Two frequencies come out, and they answer different questions:

  fmax_core   1 / (in-design combinational delay) at the tightest closing point.
              The unit's own speed. Use this to compare functional units.

  fmax_system 1 / (tightest closing period), where the period also contains the
              set_input_delay + set_output_delay reservation for surrounding
              logic. Use this to ask "what cycle time can a pipeline stage
              containing this unit hit".

Run:
    .venv/bin/python timing_closure.py --design demo_alu
    .venv/bin/python timing_closure.py --design ibex_alu_wrapper
    .venv/bin/python timing_closure.py --design demo_alu --sweep 1.0 1.5 2.0 3.0
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

import sc_flow

ROOT = Path(__file__).resolve().parent

# Matches the fraction the checked-in SDCs use, so a sweep point at the original
# period reproduces the original run exactly.
IO_DELAY_FRACTION = 0.1

SDC_TEMPLATE = """# GENERATED by timing_closure.py -- do not edit.
# Virtual-clock constraint for a combinational functional unit at a {period:.4f} ns
# target. {frac:.0%} of the period is reserved at each of the input and output
# boundary for surrounding logic, so reported slack reflects the unit alone.

set clk_period {period:.4f}

create_clock -name {clock} -period $clk_period

set_input_delay  [expr {{{frac} * $clk_period}}] -clock {clock} [all_inputs]
set_output_delay [expr {{{frac} * $clk_period}}] -clock {clock} [all_outputs]
"""


def render_sdc(
    path: Path,
    period_ns: float,
    io_delay_fraction: float = IO_DELAY_FRACTION,
    clock: str = "vclk",
) -> Path:
    """Write an SDC constraining a combinational unit at ``period_ns``."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        SDC_TEMPLATE.format(period=period_ns, frac=io_delay_fraction, clock=clock)
    )
    return path


def _metric(result: Dict[str, Any], name: str) -> Optional[float]:
    entry = result.get("metrics", {}).get(name)
    if not entry:
        return None
    value = entry.get("value")
    return None if value is None else float(value)


def evaluate_at_period(
    design_top: str,
    rtl_sources: Sequence[str],
    period_ns: float,
    build_dir: Path,
    io_delay_fraction: float = IO_DELAY_FRACTION,
) -> Dict[str, Any]:
    """Synthesize + time the design under a fresh constraint at ``period_ns``."""
    tag = "p{:.4f}".format(period_ns).replace(".", "_")
    point_dir = build_dir / tag
    # The SDC lives outside the build directory: sc_flow wipes the build
    # directory when clean=True, which would delete a constraint file written
    # into it before the tool ever read it.
    sdc = render_sdc(
        build_dir / "sdc" / "{}_{}.sdc".format(design_top, tag),
        period_ns,
        io_delay_fraction,
    )
    result = sc_flow.synthesize_design_sc(
        design_top,
        list(rtl_sources),
        sdc=str(sdc),
        build_dir=str(point_dir),
        clean=True,
    )
    slack = _metric(result, "setupslack")
    core = _metric(result, "core_path_delay")
    return {
        "period_ns": period_ns,
        "status": result.get("status"),
        "setup_slack_ns": slack,
        "closed": slack is not None and slack >= 0.0,
        "core_path_delay_ns": core,
        "fmax_core_hz": (1e9 / core) if core else None,
        "cell_area_um2": _metric(result, "cellarea"),
        "cells": _metric(result, "cells"),
        "peak_power_mw": _metric(result, "peakpower"),
        "leakage_power_mw": _metric(result, "leakagepower"),
        "ppa_json": result.get("result_file"),
    }


def find_fmax(
    design_top: str,
    rtl_sources: Sequence[str],
    build_dir: Path,
    low_ns: float = 0.3,
    high_ns: float = 8.0,
    tolerance_ns: float = 0.05,
    max_iterations: int = 8,
    io_delay_fraction: float = IO_DELAY_FRACTION,
) -> Dict[str, Any]:
    """Binary-search the tightest period the design still closes at.

    ``high_ns`` must close and ``low_ns`` is assumed not to; the search narrows
    until the bracket is within ``tolerance_ns``.  Re-synthesis happens at every
    point, so each trial is a genuine delay-driven mapping rather than a re-time
    of one area-mapped netlist.
    """
    trials: List[Dict[str, Any]] = []

    ceiling = evaluate_at_period(
        design_top, rtl_sources, high_ns, build_dir, io_delay_fraction
    )
    trials.append(ceiling)
    if not ceiling["closed"]:
        return {
            "design": design_top,
            "status": "fail",
            "error": "upper bound {:.3f} ns does not close; raise --high".format(high_ns),
            "trials": trials,
        }

    best = ceiling
    lo, hi = low_ns, high_ns
    for _ in range(max_iterations):
        if hi - lo <= tolerance_ns:
            break
        mid = 0.5 * (lo + hi)
        trial = evaluate_at_period(
            design_top, rtl_sources, mid, build_dir, io_delay_fraction
        )
        trials.append(trial)
        if trial["closed"]:
            hi, best = mid, trial
        else:
            lo = mid

    core = best["core_path_delay_ns"]
    return {
        "design": design_top,
        "status": "pass",
        "io_delay_fraction": io_delay_fraction,
        "min_closing_period_ns": best["period_ns"],
        "search_resolution_ns": hi - lo,
        "core_path_delay_ns": core,
        "fmax_core_hz": (1e9 / core) if core else None,
        "fmax_system_hz": 1e9 / best["period_ns"],
        "cell_area_um2": best["cell_area_um2"],
        "cells": best["cells"],
        "peak_power_mw": best["peak_power_mw"],
        "leakage_power_mw": best["leakage_power_mw"],
        "closing_point": best,
        "trials": trials,
    }


# --- design registry ---------------------------------------------------------
# Kept tiny on purpose: a design is a top module plus the sources feeding it.
# Ibex needs its sv2v-converted Verilog, which its adapter produces.

def _ibex_sources() -> List[str]:
    converted = ROOT / "build" / "sc_ibex" / "ibex_alu_wrapper.v"
    if not converted.is_file():
        raise SystemExit(
            "Ibex needs its sv2v output. Run `make ppa-ibex` once first "
            "(expected at {}).".format(converted)
        )
    return [str(converted)]


DESIGNS = {
    "demo_alu": lambda: [str(ROOT / "rtl" / "demo_alu.sv")],
    "demo_alu_manual_fused": lambda: [str(ROOT / "rtl" / "demo_alu_manual_fused.sv")],
    "ibex_alu_wrapper": _ibex_sources,
}


def _print_report(report: Dict[str, Any]) -> None:
    if report.get("status") != "pass":
        print("FAILED: {}".format(report.get("error")))
        return
    print("\n=== {} : timing closure ===".format(report["design"]))
    print("  {:<28} {:>10}  {:>10}  {:>8}".format("period (ns)", "slack (ns)", "core (ns)", "closes"))
    for trial in sorted(report["trials"], key=lambda t: -t["period_ns"]):
        print("  {:<28.3f} {:>10}  {:>10}  {:>8}".format(
            trial["period_ns"],
            "{:.3f}".format(trial["setup_slack_ns"]) if trial["setup_slack_ns"] is not None else "-",
            "{:.3f}".format(trial["core_path_delay_ns"]) if trial["core_path_delay_ns"] else "-",
            "yes" if trial["closed"] else "NO",
        ))
    print("\n  min closing period : {:.3f} ns (+/- {:.3f})".format(
        report["min_closing_period_ns"], report["search_resolution_ns"]))
    print("  critical path      : {:.3f} ns".format(report["core_path_delay_ns"]))
    print("  fmax_core          : {:.1f} MHz   <- the unit's own speed".format(
        report["fmax_core_hz"] / 1e6))
    print("  fmax_system        : {:.1f} MHz   (incl. {:.0%} I/O budget each side)".format(
        report["fmax_system_hz"] / 1e6, report["io_delay_fraction"]))
    print("  area at closure    : {:.1f} um^2 ({:.0f} cells)".format(
        report["cell_area_um2"], report["cells"]))


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--design", default="demo_alu", choices=sorted(DESIGNS))
    parser.add_argument("--sweep", type=float, nargs="+",
                        help="Explicit periods (ns) instead of a binary search")
    parser.add_argument("--low", type=float, default=0.3, help="Search lower bound (ns)")
    parser.add_argument("--high", type=float, default=8.0, help="Search upper bound (ns)")
    parser.add_argument("--tolerance", type=float, default=0.05, help="Bracket width (ns)")
    parser.add_argument("--io-delay-fraction", type=float, default=IO_DELAY_FRACTION)
    parser.add_argument("--output", default="build/timing_closure")
    args = parser.parse_args(argv)

    sources = DESIGNS[args.design]()
    build_dir = Path(args.output).resolve() / args.design

    if args.sweep:
        trials = [
            evaluate_at_period(args.design, sources, p, build_dir, args.io_delay_fraction)
            for p in sorted(args.sweep, reverse=True)
        ]
        closing = [t for t in trials if t["closed"]]
        best = min(closing, key=lambda t: t["period_ns"]) if closing else None
        report = {
            "design": args.design,
            "status": "pass" if best else "fail",
            "io_delay_fraction": args.io_delay_fraction,
            "trials": trials,
        }
        if best:
            core = best["core_path_delay_ns"]
            report.update({
                "min_closing_period_ns": best["period_ns"],
                "search_resolution_ns": 0.0,
                "core_path_delay_ns": core,
                "fmax_core_hz": (1e9 / core) if core else None,
                "fmax_system_hz": 1e9 / best["period_ns"],
                "cell_area_um2": best["cell_area_um2"],
                "cells": best["cells"],
                "peak_power_mw": best["peak_power_mw"],
                "leakage_power_mw": best["leakage_power_mw"],
                "closing_point": best,
            })
        else:
            report["error"] = "no swept period closed"
    else:
        report = find_fmax(
            args.design, sources, build_dir,
            low_ns=args.low, high_ns=args.high,
            tolerance_ns=args.tolerance,
            io_delay_fraction=args.io_delay_fraction,
        )

    out = build_dir / "timing_closure.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2, sort_keys=True))
    _print_report(report)
    print("\nwrote {}".format(out))
    return 0 if report.get("status") == "pass" else 1


if __name__ == "__main__":
    sys.exit(main())
