// Generated by graph_rtl_emit.py from fu-executable-graph/v1.
// This file is generic RTLIL-subset output; no template body is used.
module egglog_spike (
    input logic [7:0] x_i,
    output logic [7:0] y_o
);

    assign y_o = x_i;
endmodule
