--language
1800-2017
--timing
--assert
-Wall
--binary
-j
1
--Mdir
/home/dabinford/research/meeting-artifacts/graph-backends/egglog-spike/simulation/obj_dir
--prefix
Vtb_egglog_spike
--top-module
tb_egglog_spike
--compiler
gcc
-MAKEFLAGS
CXX=/home/dabinford/research/tools/mm/root/envs/eda/bin/g++
-MAKEFLAGS
LINK=/home/dabinford/research/tools/mm/root/envs/eda/bin/g++
/home/dabinford/research/meeting-artifacts/graph-backends/egglog-spike/egglog_spike.sv
/home/dabinford/research/meeting-artifacts/graph-backends/egglog-spike/tb_egglog_spike.sv
