/* Generated by Yosys 0.67+34 (git sha1 d4f39588a, Release, Clang /usr/bin/clang++ 18.1.8) */

module generated_fused_add_mul_mac(clk_i, rst_ni, valid_i, mode_i, a_i, b_i, c_i, ready_o, valid_o, result_o);
  input clk_i;
  wire clk_i;
  input rst_ni;
  wire rst_ni;
  input valid_i;
  wire valid_i;
  input [1:0] mode_i;
  wire [1:0] mode_i;
  input [31:0] a_i;
  wire [31:0] a_i;
  input [31:0] b_i;
  wire [31:0] b_i;
  input [31:0] c_i;
  wire [31:0] c_i;
  output ready_o;
  wire ready_o;
  output valid_o;
  reg valid_o;
  output [63:0] result_o;
  reg [63:0] result_o;
  wire _00_;
  wire _01_;
  wire _02_;
  wire [63:0] _03_;
  wire [63:0] add_input;
  wire [63:0] add_result;
  wire [63:0] product;
  wire [63:0] selected_result;
  assign add_result = add_input + _03_;
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) result_o <= 64'h0000000000000000;
    else if (valid_i) result_o <= selected_result;
  assign product = a_i * b_i;
  always @(posedge clk_i, negedge rst_ni)
    if (!rst_ni) valid_o <= 1'h0;
    else valid_o <= valid_i;
  function [63:0] _08_;
    input [63:0] a;
    input [191:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _08_ = b[63:0];
      3'b?1?:
        _08_ = b[127:64];
      3'b1??:
        _08_ = b[191:128];
      default:
        _08_ = a;
    endcase
  endfunction
  assign selected_result = _08_(64'h0000000000000000, { add_result, product, add_result }, { _02_, _01_, _00_ });
  assign _00_ = mode_i == 2'h2;
  assign _01_ = mode_i == 2'h1;
  assign _02_ = ! mode_i;
  assign add_input = _00_ ? product : { 32'h00000000, a_i };
  assign _03_ = _00_ ? { 32'h00000000, c_i } : { 32'h00000000, b_i };
  assign ready_o = rst_ni;
endmodule
