// Generated by graph_rtl_emit.py from fu-executable-graph/v1.
// This file is generic RTLIL-subset output; no template body is used.
module graph_fused_unit (
    input logic [31:0] a_a_i,
    input logic [31:0] a_b_i,
    input logic add_mode_b_i,
    input logic [31:0] b_a_i,
    input logic [31:0] b_b_i,
    input logic [31:0] c_b_i,
    input logic mac_mode_b_i,
    input logic mul_mode_b_i,
    input logic source_select_i,
    output logic [63:0] product_a_o,
    output logic [63:0] result_b_o
);
    logic [63:0] w_adapter_const_output_product_a_o;
    logic [63:0] w_adapter_const_output_result_b_o;
    logic [63:0] w_adapter_mux_output_product_a_o;
    logic [63:0] w_adapter_mux_output_result_b_o;
    logic [31:0] w_adapter_mux_shared_operator_A;
    logic [31:0] w_adapter_mux_shared_operator_B;
    logic [63:0] w_b__add__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_20_5;
    logic [63:0] w_b__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_17_2;
    logic [63:0] w_b__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_18_4;
    logic [63:0] w_b__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_19_3;
    logic [63:0] w_b__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_20_6;
    logic [63:0] w_b_adapter_concat__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_17_2_B;
    logic [63:0] w_b_adapter_concat__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_18_4_B;
    logic [63:0] w_b_adapter_concat__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_19_3_B;
    logic [31:0] w_b_const__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_17_2_B;
    logic [31:0] w_b_const__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_18_4_B;
    logic [63:0] w_b_const__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_19_3_A;
    logic [31:0] w_b_const__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_19_3_B;
    logic [63:0] w_shared_operator;

    assign w_adapter_const_output_product_a_o = 64'b0000000000000000000000000000000000000000000000000000000000000000;
    assign w_adapter_const_output_result_b_o = 64'b0000000000000000000000000000000000000000000000000000000000000000;
    assign w_b_const__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_17_2_B = 32'b00000000000000000000000000000000;
    assign w_b_const__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_18_4_B = 32'b00000000000000000000000000000000;
    assign w_b_const__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_19_3_A = 64'b0000000000000000000000000000000000000000000000000000000000000000;
    assign w_b_const__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_19_3_B = 32'b00000000000000000000000000000000;
    assign w_b_adapter_concat__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_17_2_B = {w_b_const__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_17_2_B, a_b_i};
    assign w_b_adapter_concat__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_18_4_B = {w_b_const__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_18_4_B, b_b_i};
    assign w_b_adapter_concat__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_19_3_B = {w_b_const__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_19_3_B, c_b_i};
    assign w_adapter_mux_shared_operator_A = source_select_i ? a_a_i : a_b_i;
    assign w_adapter_mux_shared_operator_B = source_select_i ? b_a_i : b_b_i;
    assign w_b__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_19_3 = mac_mode_b_i ? w_b_adapter_concat__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_19_3_B : w_b_const__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_19_3_A;
    assign w_shared_operator = w_adapter_mux_shared_operator_A * w_adapter_mux_shared_operator_B;
    assign w_b__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_18_4 = add_mode_b_i ? w_b_adapter_concat__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_18_4_B : w_b__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_19_3;
    assign w_b__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_17_2 = add_mode_b_i ? w_b_adapter_concat__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_17_2_B : w_shared_operator;
    assign w_adapter_mux_output_product_a_o = source_select_i ? w_shared_operator : w_adapter_const_output_product_a_o;
    assign w_b__add__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_20_5 = w_b__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_17_2 + w_b__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_18_4;
    assign w_b__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_20_6 = mul_mode_b_i ? w_shared_operator : w_b__add__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_20_5;
    assign w_adapter_mux_output_result_b_o = source_select_i ? w_adapter_const_output_result_b_o : w_b__ternary__home_dabinford_research_rtl_fma_experiment_graph_unit_b_add_mul_mac_sv_20_6;
    assign product_a_o = w_adapter_mux_output_product_a_o;
    assign result_b_o = w_adapter_mux_output_result_b_o;
endmodule
