#!/usr/bin/env python3
"""Emit the contract-guided whole-Ibex module-preserving wrapper."""

import hashlib
import json
from pathlib import Path
from typing import Any, Dict


class ContractEmitError(ValueError):
    pass


def sha256(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def emit(contract: Dict[str, Any]) -> str:
    if contract.get("schema") != "fu-ibex-sharing-contract/v1":
        raise ContractEmitError("unsupported sharing contract schema")
    owner = contract.get("resource_owner") or {}
    if owner.get("module") != "ibex_alu":
        raise ContractEmitError("contract owner is not ibex_alu")
    resource = contract.get("shared_resource") or {}
    required_resource = {
        "kind": "$add", "operand_width": 33, "extended_result_width": 34,
        "architectural_result_width": 32, "architectural_result_slice": "[32:1]"
    }
    if any(resource.get(key) != value for key, value in required_resource.items()):
        raise ContractEmitError("contract does not describe the verified 33-bit Ibex adder and 34-bit result")
    interface = contract.get("interface") or {}
    required = {"operator_i", "alu_operand_a_i", "alu_operand_b_i", "client_operand_a_i",
                "client_operand_b_i", "client_select_i", "result_o"}
    if set(interface) != required:
        raise ContractEmitError("contract interface is incomplete or contains undeclared ports")
    selector = contract.get("selector") or {}
    if selector.get("port") != "client_select_i" or selector.get("width") != 1:
        raise ContractEmitError("contract selector is invalid")
    paths = contract.get("operand_paths") or {}
    expected = {"alu_a": "{alu_operand_a_i,1'b1}", "alu_b": "{alu_operand_b_i,1'b0}",
                "client_a": "{client_operand_a_i,1'b1}", "client_b": "{client_operand_b_i,1'b0}"}
    if paths != expected:
        raise ContractEmitError("contract operand encoding does not match verified Ibex paths")
    top = contract.get("generated_top")
    if not isinstance(top, str) or not top:
        raise ContractEmitError("contract lacks generated top")
    # The module body is assembled from the contract's owner, interface,
    # selector, paths, and result-routing declarations.  It preserves the
    # upstream module instance rather than reconstructing or flattening it.
    return """`timescale 1ns/1ps
// Generated by ibex_module_preserving_emit.py.
// Classification: contract-guided module-preserving fusion.
module {top}
  import ibex_pkg::*;
(
  input  logic [6:0]  operator_i,
  input  logic [31:0] alu_operand_a_i,
  input  logic [31:0] alu_operand_b_i,
  input  logic [31:0] client_operand_a_i,
  input  logic [31:0] client_operand_b_i,
  input  logic        client_select_i,
  output logic [31:0] result_o
);
  alu_op_e effective_operator;
  logic [31:0] alu_result;
  logic comparison_result;
  logic equal_result_unused;
  logic [31:0] imd_val_d_unused [2];
  logic [1:0] imd_val_we_unused;
  logic [31:0] adder_result;
  logic [33:0] adder_result_ext_unused;

  assign effective_operator = client_select_i ? ALU_ADD : alu_op_e'(operator_i);
  ibex_alu #(.RV32B(RV32BNone)) u_owner (
    .operator_i(effective_operator),
    .operand_a_i(alu_operand_a_i), .operand_b_i(alu_operand_b_i),
    .instr_first_cycle_i(1'b1),
    .multdiv_operand_a_i({{client_operand_a_i, 1'b1}}),
    .multdiv_operand_b_i({{client_operand_b_i, 1'b0}}),
    .multdiv_sel_i(client_select_i),
    .imd_val_q_i('{{32'b0, 32'b0}}), .imd_val_d_o(imd_val_d_unused),
    .imd_val_we_o(imd_val_we_unused), .adder_result_o(adder_result),
    .adder_result_ext_o(adder_result_ext_unused), .result_o(alu_result),
    .comparison_result_o(comparison_result),
    .is_equal_result_o(equal_result_unused)
  );

  always_comb begin
    if (client_select_i) begin
      result_o = adder_result;
    end else begin
      unique case (effective_operator)
        ALU_LT, ALU_LTU, ALU_GE, ALU_GEU, ALU_EQ, ALU_NE:
          result_o = {{31'b0, comparison_result}};
        default: result_o = alu_result;
      endcase
    end
  end
endmodule
""".format(top=top)


def write(contract_path: Path, output_path: Path) -> str:
    contract = json.loads(Path(contract_path).read_text())
    text = emit(contract)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(text)
    return text


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("contract", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    write(args.contract, args.output)
