`timescale 1ns/1ps
// Generated by ibex_module_preserving_emit.py.
// Classification: contract-guided module-preserving fusion.
module ibex_alu_add_client_fused
  import ibex_pkg::*;
(
  input  logic [6:0]  operator_i,
  input  logic [31:0] alu_operand_a_i,
  input  logic [31:0] alu_operand_b_i,
  input  logic [31:0] client_operand_a_i,
  input  logic [31:0] client_operand_b_i,
  input  logic        client_select_i,
  output logic [31:0] result_o
);
  alu_op_e effective_operator;
  logic [31:0] alu_result;
  logic comparison_result;
  logic equal_result_unused;
  logic [31:0] imd_val_d_unused [2];
  logic [1:0] imd_val_we_unused;
  logic [31:0] adder_result;
  logic [33:0] adder_result_ext_unused;

  assign effective_operator = client_select_i ? ALU_ADD : alu_op_e'(operator_i);
  ibex_alu #(.RV32B(RV32BNone)) u_owner (
    .operator_i(effective_operator),
    .operand_a_i(alu_operand_a_i), .operand_b_i(alu_operand_b_i),
    .instr_first_cycle_i(1'b1),
    .multdiv_operand_a_i({client_operand_a_i, 1'b1}),
    .multdiv_operand_b_i({client_operand_b_i, 1'b0}),
    .multdiv_sel_i(client_select_i),
    .imd_val_q_i('{32'b0, 32'b0}), .imd_val_d_o(imd_val_d_unused),
    .imd_val_we_o(imd_val_we_unused), .adder_result_o(adder_result),
    .adder_result_ext_o(adder_result_ext_unused), .result_o(alu_result),
    .comparison_result_o(comparison_result),
    .is_equal_result_o(equal_result_unused)
  );

  always_comb begin
    if (client_select_i) begin
      result_o = adder_result;
    end else begin
      unique case (effective_operator)
        ALU_LT, ALU_LTU, ALU_GE, ALU_GEU, ALU_EQ, ALU_NE:
          result_o = {31'b0, comparison_result};
        default: result_o = alu_result;
      endcase
    end
  end
endmodule
